[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings
optimizer = true
optimizer_runs = 200

# Allow multiple Solidity versions
auto_detect_solc = true

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
network = "${RPC_URL}"

[etherscan]
network = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_VERIFIER_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
